name: Fetch Fandom Templates and Modules

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl jq python3

      - name: Make script executable
        run: chmod +x fetch_templates.sh

      - name: Run fetch script
        run: ./fetch_templates.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: fandom-templates
          path: wiki_resources/fandom_templates.xml
